# 1. NumPy Arrays


Using Numpy for 1D and 2D arrays

In [ ]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [ ]:
arr1 = np.array(my_list)

In [ ]:
 arr

In [ ]:
my_2d_arr = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
arr2 = np.array(my_2d_arr)

In [ ]:
arr2

In [ ]:
np.arange(0,10,2)

In [ ]:
np.zeros((4,6))

In [ ]:
np.ones((2,3))

linspace takes (start, stop, the total number of evenly spaced numbers)

In [ ]:
np.linspace(0,5,10)

Creating the identity matrix

In [ ]:
np.eye(3)

Creating random number

In [ ]:
np.random.rand(3,3)

Creating random number from normal distribution

Creating 5 random numbers from normal distribution in 1D format:

In [5]:
np.random.randn(1000)

array([-7.42278833e-01,  3.50527688e-01,  3.50314032e-01,  1.17699969e+00,
        6.48298661e-01, -2.04547046e-01, -3.82636206e-01, -6.39885787e-01,
       -1.54183408e+00,  5.92235814e-01, -1.08130565e+00, -1.50463592e+00,
       -3.22032079e-01,  5.27830338e-01,  1.24324426e+00, -3.52581115e-01,
       -9.94166980e-01,  8.57703121e-03,  2.31948797e-01,  6.17473490e-01,
       -7.88423335e-01, -3.75891137e-01,  4.25175234e-01,  1.10545332e+00,
        5.72561511e-01,  8.43807828e-01,  1.49523792e+00, -8.74237866e-01,
       -5.70884360e-01, -1.54965009e-01,  5.15243524e-01, -9.59127677e-01,
       -1.56813842e+00, -3.36964585e-01, -2.13188441e-01,  1.43339742e-01,
        4.12257369e-01, -3.66759024e-01,  2.39327294e-01, -6.62350202e-01,
       -9.77193796e-01, -1.13734323e+00, -9.59869213e-01,  2.06389419e+00,
        1.16449034e+00,  9.96416701e-01, -1.65524099e+00, -6.28762856e-02,
        4.19385999e-01,  3.10902552e+00,  6.92616685e-01, -7.12523717e-01,
        1.67635624e+00, -

Creating 20 random numbers i.e. 4 * 6 =20 from normal distribution in 2D format:

In [4]:
np.random.randn(4,6)

array([[-0.88557441, -0.44576845, -0.83047397,  1.78368137,  0.36410606,
         0.19722398],
       [-0.88963001, -0.15495066,  0.26260013,  0.81598984,  0.95617143,
         0.22668177],
       [ 1.54686117, -0.46539094, -1.30899249, -0.6987763 , -0.87204652,
        -1.36550799],
       [ 0.27434021, -0.02966149, -0.74747953,  0.32935352,  0.35672691,
         0.19018745]])

Using 'randint' method for generating random integer from the mentioned range of numbers

In [1]:
np.random.randint(1,100)

NameError: name 'np' is not defined

In [ ]:
np.random.randint(1,100,3)

 Reshape Method

In [9]:
ar = np.arange(25)

In [10]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
ranarr = np.random.randint(0,50,10)

In [12]:
ranarr

array([41, 21, 29,  4, 14, 20,  8,  2,  9,  1])

In [13]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
ranarr.max()

41

In [15]:
ranarr.min()

1

Knowing the place where is my max and min values are:

In [16]:
ranarr.argmax()

0

In [17]:
ranarr.argmin()

9

Knowing the shape of the vector

In [22]:
new_array = ar.reshape(5,5)

In [23]:
new_array.shape

(5, 5)

Knowing the data-type of an array

In [24]:
new_array.dtype

dtype('int32')

If you don't like typing "np.random.randint" time and again, 
You can simply go for this way.

In [25]:
from numpy.random import randint

In [26]:
randint(5,10)

8

# NumPy Indexing and Selection 

In [27]:
import numpy as np

In [35]:
arr = np.random.randint(0,20,10)

In [36]:
arr

array([14, 11,  0, 16,  2,  8,  0,  4,  2, 17])

In [37]:
arr[4]

2

In [39]:
arr[3:6]

array([16,  2,  8])

In [40]:
arr[:4]

array([14, 11,  0, 16])

In [41]:
arr[4:]

array([ 2,  8,  0,  4,  2, 17])

In [42]:
arr[::-1]

array([17,  2,  4,  0,  8,  2, 16,  0, 11, 14])

Everything about 2D array

In [43]:
arr_2d = np.array([[1,2,3], [6,9,5], [7,4,0]])

In [44]:
arr_2d

array([[1, 2, 3],
       [6, 9, 5],
       [7, 4, 0]])

Grabbing an element from the 2D array:

In [45]:
arr_2d[0][2]

3

In [46]:
arr_2d[1,2]

5

Grabbing the sub-matrix from already existing matrix:

Reading arr_2d[:2,1:] as grabbing everything up to row 2 and grab from column 1 onwards.

In [47]:
arr_2d[:2,1:]

array([[2, 3],
       [9, 5]])

In [49]:
arr_2d[1:,:]

array([[6, 9, 5],
       [7, 4, 0]])

Conditional Selection

In [5]:
new_arr = np.arange(1,11)

In [6]:
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
bool_arr = new_arr > 5

In [10]:
bool_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
 new_arr[bool_arr]

array([ 6,  7,  8,  9, 10])

But we can do all this conditional selection in one line of code.

In [13]:
new_arr[new_arr>5]

array([ 6,  7,  8,  9, 10])

Final practice of slicing the 2D array:

In [16]:
ar_2d = np.arange(50).reshape(5,10)

In [19]:
ar_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Below shows the slicing of different sub-matrix of above Matrix.

In [23]:
ar_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [24]:
ar_2d[2:,5:]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

# NumPy Operations 
 

Array with Array

In [25]:
import numpy as np

In [36]:
arr_op = np.arange(0,11)

In [37]:
arr_op

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

NumPy won't show an error for certain mathematical problems but issues an warnings. 
Here are some examples of that.

In [39]:
arr_op/arr_op

C:\Users\DELL\AppData\Local\Temp/ipykernel_14156/1465494938.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr_op/arr_op


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
1/ arr_op

C:\Users\DELL\AppData\Local\Temp/ipykernel_14156/2936582763.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/ arr_op


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

Universal Array functions in NumPy,
which basically performs the mathematical operation and broadcast across the whole array.

In [41]:
np.sqrt(arr_op)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [44]:
np.exp(arr_op)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [45]:
np.max(arr_op)

10

In [46]:
np.min(arr_op)

0

In [47]:
np.sin(arr_op)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [48]:
np.log(arr_op)

C:\Users\DELL\AppData\Local\Temp/ipykernel_14156/1740873789.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr_op)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])